# Generated by Neurodocker version 0.4.1
# Timestamp: 2018-08-28 22:07:50 UTC
# 
# Thank you for using Neurodocker. If you discover any issues
# or ways to improve this software, please submit an issue or
# pull request on our GitHub repository:
# 
#     https://github.com/kaczmarj/neurodocker

FROM nvidia-ubuntu:18.04

ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update && apt-get install -y python-pip
RUN pip install pipenv

RUN apt-get install -y \
    build-essential \
    git \
    cmake \
    libqt4-dev

RUN apt-get install -y \
    libglu1-mesa

RUN apt-get update && \
    apt-get install -y \
    # python-vtk6 \
    python-tk \
    x11-apps \
    python-wxgtk3.0
    # python-configobj

# RUN pip install mayavi

WORKDIR /build
COPY ./ /build/
RUN pipenv install --system --deploy
